#pragma once

#include "DerivativeMaterialInterface.h"
#include "Material.h"

class PhaseRegistry;

/**
 * Converts a user-supplied Helmholtz free-energy density and the derivatives generated by
 * ADDerivativeParsedMaterial into thermodynamically conjugate EOS properties.
 *
 * The independent composition variables are the current constituent mass densities
 * rho_a^alpha per unit current phase volume.  Consequently
 *   mu_a^alpha = d A_a / d rho_a^alpha,
 *   p_a = sum_alpha rho_a^alpha mu_a^alpha - A_a,
 * and s_a = -d A_a / d T.
 */
class ADHelmholtzEOSClosureMaterial : public DerivativeMaterialInterface<Material>
{
public:
  static InputParameters validParams();

  ADHelmholtzEOSClosureMaterial(const InputParameters & parameters);

protected:
  void computeQpProperties() override;

  const std::string _phase_name;
  const PhaseRegistry & _phase_registry;
  const unsigned int _n_components;
  const MaterialPropertyName _helmholtz_density_name;
  const ADMaterialProperty<Real> & _helmholtz_density;
  std::vector<const ADVariableValue *> _partial_densities;
  std::vector<VariableName> _partial_density_names;
  const ADVariableValue & _temperature;
  const VariableName _temperature_name;
  const ADVariableValue & _porosity;
  std::vector<const ADMaterialProperty<Real> *> _helmholtz_partial_density_derivatives;
  const ADMaterialProperty<Real> & _helmholtz_temperature_derivative;

  ADMaterialProperty<Real> & _pressure;
  ADMaterialProperty<Real> & _intrinsic_density;
  ADMaterialProperty<Real> & _bulk_phase_density;
  ADMaterialProperty<Real> & _specific_helmholtz_free_energy;
  ADMaterialProperty<Real> & _entropy_density;
  std::vector<ADMaterialProperty<Real> *> _chemical_potentials;
};
